package com.example.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    BANGLA("bn", "Bangla", "বাংলা")
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.BANGLA }

object Strings {
    private val en = mapOf(
        "app_title" to "NetBill ISP Professional",
        "currency_symbol" to "৳",
        "currency_code" to "BDT",
        
        // Navigation
        "dashboard" to "Dashboard",
        "dashboard_title" to "Dashboard",
        "customer_crm" to "Customer CRM",
        "customers" to "Customer CRM",
        "mikrotik" to "MikroTik Router Management",
        "mikrotik_title" to "MikroTik Router Management",
        "billing" to "Billing Management",
        "billing_title" to "Billing Management",
        "payments" to "Payments & Collections",
        "payments_title" to "Payments & Collections",
        "expenses" to "Expense Management",
        "expense_title" to "Expense Management",
        "staff" to "Staff Management",
        "staff_title" to "Staff Management",
        "packages" to "Packages & Tariffs",
        "packages_title" to "Packages & Tariffs",
        "reports" to "Reports & Analytics",
        "reports_title" to "Reports & Analytics",
        "notifications" to "SMS Notifications",
        "sms_title" to "SMS Notifications",
        "sms_tracker_title" to "Automated SMS Delivery & Status Tracker",
        "sms_tracker_desc" to "Real-time delivery confirmation for billing alerts, support updates & payment receipts",
        "status_all" to "All Statuses",
        "status_delivered" to "Delivered",
        "status_failed" to "Failed",
        "status_pending" to "Pending",
        "type_all" to "All Types",
        "type_billing_alert" to "Billing Alert",
        "type_support_update" to "Support Update",
        "type_payment_receipt" to "Payment Receipt",
        "type_20th_reminder" to "20th Day Reminder",
        "total_sent_sms" to "Total Sent SMS",
        "delivered_rate" to "Delivery Success Rate",
        "resend_failed" to "Resend Failed SMS",
        "send_support_sms" to "Send Support Update SMS",
        "resend_now" to "Resend Now",
        "clear_logs" to "Clear Tracker History",
        "backup" to "Database Backup",
        "backup_title" to "Database Backup",
        "settings" to "Settings",
        "settings_title" to "Settings",
        "logout" to "Logout",
        "nav_dashboard" to "Dashboard",
        "nav_customers" to "Customers",
        "nav_billing" to "Billing",
        "nav_payments" to "Payments",
        "nav_router" to "Router",

        // Customer Ledger
        "customer_ledger" to "Customer Ledger",
        "view_ledger" to "View Complete Ledger",
        "ledger_summary" to "Financial Summary",
        "ledger_timeline" to "Ledger Timeline",
        "current_due" to "Current Due",
        "previous_due" to "Previous Due",
        "carry_forward_due" to "Carry Forward Due",
        "total_generated_bill" to "Total Generated Bill",
        "total_paid" to "Total Paid",
        "total_discount" to "Total Discount",
        "total_advance" to "Total Advance",
        "net_outstanding" to "Net Outstanding",
        "running_balance" to "Running Balance",
        "add_ledger_entry" to "Add Ledger Entry",
        "download_receipt" to "Download Receipt",
        "print_receipt" to "Print Receipt",
        "share_receipt" to "Share Receipt",
        "export_ledger" to "Export Ledger Statement",
        "filter_type" to "Filter Type",
        "all_types" to "All Types",
        "entry_type" to "Entry Type",
        "monthly_bill" to "Monthly Bill",
        "payment" to "Payment",
        "discount" to "Discount",
        "advance" to "Advance",
        "adjustment" to "Adjustment",
        "carry_forward" to "Carry Forward Due",
        "manual_charge" to "Manual Charge",
        "refund" to "Refund",
        "waiver" to "Waiver",

        // Auth
        "login_title" to "NetBill ISP Management",
        "login_subtitle" to "Professional ISP Billing Software Bangladesh",
        "username" to "Username",
        "password" to "Password",
        "mobile_number" to "Mobile Number (01XXXXXXXXX)",
        "login_btn" to "Login to Dashboard",
        "role" to "Role",
        "super_admin" to "Super Admin",
        "manager" to "Manager",
        "billing_operator" to "Billing Operator",
        "support_staff" to "Support Staff",
        "use_mobile_login" to "Login with Mobile Number",
        "use_user_pass_login" to "Login with Username / Password",
        "login_success" to "Logged in successfully!",
        "invalid_credentials" to "Invalid username or password",

        // Dashboard
        "total_customers" to "Total Customers",
        "todays_collection" to "Today's Collection",
        "collection_breakdown" to "Collection Breakdown",
        "yesterday" to "Yesterday",
        "last_7_days" to "Last 7 Days",
        "this_month" to "This Month",
        "custom_date" to "Custom Date",
        "total_transactions" to "Total Transactions",
        "avg_collection" to "Average Collection",
        "highest_collection" to "Highest Single",
        "lowest_collection" to "Lowest Single",
        "other_methods" to "Other",
        "grand_total" to "Grand Total",
        "select_date" to "Select Date",
        "monthly_collection" to "Monthly Collection",
        "total_due" to "Total Due",
        "todays_expense" to "Today's Expense",
        "monthly_expense" to "Running Month Expense",
        "active_customers" to "Active Customers",
        "expired_customers" to "Expired Customers",
        "inactive_customers" to "Inactive Customers",
        "new_customers" to "New Customers (This Month)",
        "bandwidth_usage" to "Bandwidth Usage",
        "monthly_income_graph" to "Monthly Income Analysis",
        "expense_graph" to "Expense Breakdown",
        "customer_growth" to "Customer Growth Trend",
        "quick_actions" to "Quick Actions",
        "add_customer" to "Add Customer",
        "collect_payment" to "Collect Payment",
        "generate_bills" to "Generate Monthly Bills",
        "grid_collection" to "Collection",
        "grid_collection_report" to "Collection Report",
        "grid_list_report" to "List Report",
        "grid_due_list" to "Due List",
        "grid_create_new" to "Create New",
        "grid_search" to "Search",
        "grid_complaint_list" to "Complin List",
        "grid_bill_summary" to "Bill Summary",

        // Customer Management
        "customer_crm" to "Customer CRM",
        "customer_id" to "Customer ID",
        "customer_name" to "Customer Name",
        "alt_mobile" to "Alt Mobile",
        "address" to "Address",
        "zone" to "Zone",
        "sub_zone" to "Sub Zone",
        "network_box" to "Network Box (TJ/Splitter)",
        "package_name" to "Internet Package",
        "monthly_bill" to "Monthly Bill Amount",
        "pppoe_username" to "PPPoE Username",
        "pppoe_password" to "PPPoE Password",
        "ip_address" to "IP Address",
        "mac_address" to "MAC Address",
        "connection_type" to "Connection Type",
        "join_date" to "Join Date",
        "expire_date" to "Expire Date",
        "status" to "Status",
        "active" to "Active",
        "inactive" to "Inactive",
        "suspended" to "Suspended",
        "ref_name" to "Reference Name",
        "ref_mobile" to "Reference Mobile",
        "current_due" to "Current Due",
        "notes" to "Notes",
        "search_customer" to "Search customer by name, ID, phone, PPPoE...",
        "filter_zone" to "Filter Zone",
        "filter_package" to "Filter Package",
        "filter_status" to "Filter Status",
        "due_customers" to "Due Customers Only",
        "all_zones" to "All Zones",
        "all_packages" to "All Packages",
        "all_status" to "All Statuses",
        "save_customer" to "Save Customer Info",
        "edit_customer" to "Edit Customer",
        "delete_customer" to "Delete Customer",
        "customer_saved" to "Customer saved successfully",
        
        // Expiry Alert & Customer Expiry Management
        "customer_expiry_alert_title" to "Customer Expiry Alert!",
        "customer_expiry_alert_desc" to "Alerts for customers whose line validity will expire tomorrow.",
        "expiring_tomorrow_count" to "customers will expire tomorrow.",
        "view_alerts" to "View Alerts",
        "no_upcoming_expiry" to "No upcoming customer expiry",
        "expiring_tomorrow" to "Expiring Tomorrow",
        "expired" to "Expired",
        "total_due" to "Total Outstanding Due",
        "expire_date" to "Expire Date",
        "expire_time" to "Expire Time",
        "extend_expiry" to "Extend Expiry",
        "update_expiry" to "Update Expiry",
        "customer_name" to "Customer Name",
        "address" to "Address",
        "mobile_number" to "Mobile Number",

        // 20th Day Rule
        "day_20_rule_title" to "Special Billing Rule (Joined after 20th)",
        "day_20_rule_desc" to "This customer joined after the 20th day of the month. How would you like to handle billing?",
        "gen_current_month" to "Generate Current Month Bill Now",
        "gen_next_month" to "Start Billing From Next Month",
        "day_20_deadline_alert_title" to "Customer Expiry Alerts",
        "day_20_deadline_alert_desc" to "Alerts for customers whose line validity will expire tomorrow.",
        "overdue_20th_count" to "Expiring Customers (Tomorrow)",
        "overdue_20th_amount" to "Total Outstanding Due",
        "send_sms_all_20th" to "Send SMS Reminder to Expiring Customers",
        "suspend_all_20th" to "Suspend Expired Lines",
        "dismiss_alert" to "Dismiss Alert",
        "deadline_status_active" to "Expiring Tomorrow!",

        // MikroTik
        "mikrotik_title" to "MikroTik Router Management",
        "router_status" to "Router Status",
        "router_ip" to "Router IP Address",
        "online_users" to "Online PPPoE Users",
        "user_traffic" to "Live User Traffic",
        "enable_user" to "Enable Connection",
        "disable_user" to "Disable Connection",
        "change_package" to "Change Speed/Package",
        "router_connected" to "Connected (RouterOS v7.12)",
        "router_disconnected" to "Disconnected / Checking...",
        "sync_mikrotik" to "Sync with Router",

        // Billing Module
        "billing_management" to "Billing & Invoicing",
        "invoice_no" to "Invoice #",
        "billing_month" to "Billing Month",
        "paid" to "Paid",
        "unpaid" to "Unpaid",
        "partial" to "Partial Payment",
        "generate_monthly_invoices" to "Generate Auto Monthly Bills",
        "bills_generated" to "Monthly Invoices Generated Successfully!",
        "late_fee" to "Late Payment Fee",
        "previous_due" to "Previous Due",
        "total_payable" to "Total Payable",

        // Payment Collection
        "payment_collection" to "Payment Collection",
        "amount" to "Amount (৳)",
        "payment_method" to "Payment Method",
        "bkash" to "bKash",
        "nagad" to "Nagad",
        "rocket" to "Rocket",
        "cash" to "Cash",
        "bank_transfer" to "Bank Transfer",
        "transaction_id" to "Transaction ID / Ref",
        "payment_date" to "Payment Date",
        "collector_name" to "Collected By",
        "remarks" to "Remarks",
        "record_payment" to "Record Payment",
        "payment_success" to "Payment Recorded Successfully!",
        "view_receipt" to "View / Print Receipt",
        "print_receipt" to "Print PDF Receipt",
        "share_whatsapp" to "Send WhatsApp Receipt",
        "send_sms" to "Send SMS Receipt",

        // Expenses
        "expense_management" to "Expense Management",
        "add_expense" to "Add Expense",
        "expense_category" to "Expense Category",
        "bandwidth_cost" to "Bandwidth Cost",
        "staff_salary" to "Staff Salary",
        "electricity_bill" to "Electricity Bill",
        "equipment_purchase" to "Equipment Purchase",
        "office_rent" to "Office Rent",
        "maintenance" to "Maintenance",
        "transport" to "Transport",
        "other_expense" to "Other Expense",

        // Staff
        "staff_management" to "Staff Management",
        "staff_name" to "Staff Name",
        "salary" to "Monthly Salary",
        "joining_date" to "Joining Date",
        "pay_salary" to "Disburse Salary",
        "salary_ledger" to "Salary Ledger",
        "total_salary_accrued" to "Total Salary Accrued",
        "total_disbursed" to "Total Disbursed",
        "net_balance" to "Net Balance",
        "pao_na" to "Pao-na",
        "advance" to "Advance",
        "date_month" to "Date & Month",
        "transaction_type" to "Transaction Type",
        "amount_label" to "Amount",
        "account_balance" to "Account Balance",
        "remarks_label" to "Remarks",
        "salary_accrued" to "Salary Accrued",
        "cash_disbursed" to "Cash Disbursed",
        "running_bal" to "RUNNING BAL",
        "no_records" to "No Records Found",
        "edit_salary_record" to "Edit Salary Record",
        "delete_record" to "Delete Record",
        "confirm_delete_payout" to "Are you sure you want to delete this salary record? Staff balance will be reversed.",
        "update_record" to "Update Record",
        "cancel" to "Cancel",
        "target_month" to "Target Month",
        "payroll_report" to "Payroll Report",

        // Packages
        "package_management" to "Internet Packages",
        "speed" to "Bandwidth Speed",
        "monthly_price" to "Monthly Price (৳)",
        "add_package" to "Add Package",

        // Reports
        "reports_analytics" to "Reports & Analytics",
        "daily_collection_report" to "Daily Collection Report",
        "monthly_collection_report" to "Monthly Collection Report",
        "due_report" to "Due Customers Report",
        "expense_report" to "Expense Report",
        "profit_loss_report" to "Profit & Loss Statement",
        "export_pdf" to "Export PDF",
        "export_excel" to "Export CSV/Excel",

        // Settings
        "isp_name" to "ISP Company Name",
        "isp_logo" to "ISP Logo",
        "support_number" to "Support Helpline Number",
        "language_setting" to "Language Setting (ভাষা)",
        "currency_setting" to "Currency Setting",
        "save_settings" to "Save Company Info",
        "settings_saved" to "Settings Updated!",
        "switch_to_bangla" to "বাংলা ভাষায় পরিবর্তন করুন",
        "switch_to_english" to "Switch to English"
    )

    private val bn = mapOf(
        "app_title" to "নেটবিল আইএসপি প্রফেশনাল",
        "currency_symbol" to "৳",
        "currency_code" to "টাকা",

        // Navigation
        "dashboard" to "ড্যাশবোর্ড",
        "dashboard_title" to "ড্যাশবোর্ড",
        "customer_crm" to "কাস্টমার সিআরএম",
        "customers" to "কাস্টমার সিআরএম",
        "mikrotik" to "মাইক্রোটিক রাউটার",
        "mikrotik_title" to "মাইক্রোটিক রাউটার",
        "billing" to "বিলিং ম্যানেজমেন্ট",
        "billing_title" to "বিলিং ম্যানেজমেন্ট",
        "payments" to "পেমেন্ট কালেকশন",
        "payments_title" to "পেমেন্ট কালেকশন",
        "expenses" to "দৈনন্দিন খরচ",
        "expense_title" to "দৈনন্দিন খরচ",
        "staff" to "স্টাফ ম্যানেজমেন্ট",
        "staff_title" to "স্টাফ ম্যানেজমেন্ট",
        "packages" to "ইন্টারনেট প্যাকেজ",
        "packages_title" to "ইন্টারনেট প্যাকেজ",
        "reports" to "রিপোর্ট ও এনালিটিক্স",
        "reports_title" to "রিপোর্ট ও এনালিটিক্স",
        "notifications" to "এসএমএস নোটিফিকেশন",
        "sms_title" to "এসএমএস নোটিফিকেশন",
        "sms_tracker_title" to "স্বয়ংক্রিয় এসএমএস ডেলিভারি ও স্ট্যাটাস ট্র্যাকার",
        "sms_tracker_desc" to "বিলিং এলার্ট, সাপোর্ট আপডেট ও পেমেন্ট রিসিটের রিয়েল-টাইম ডেলিভারি রিপোর্ট",
        "status_all" to "সকল স্ট্যাটাস",
        "status_delivered" to "ডেলিভার্ড (সফল)",
        "status_failed" to "ব্যর্থ (ফেইল্ড)",
        "status_pending" to "অপেক্ষমাণ",
        "type_all" to "সকল টাইপ",
        "type_billing_alert" to "বিলিং এলার্ট",
        "type_support_update" to "সাপোর্ট আপডেট",
        "type_payment_receipt" to "পেমেন্ট রিসিট",
        "type_20th_reminder" to "২০ তারিখ রিমাইন্ডার",
        "total_sent_sms" to "মোট প্রেরিত এসএমএস",
        "delivered_rate" to "ডেলিভারি সফলতা",
        "resend_failed" to "ব্যর্থ এসএমএস পুনরায় পাঠান",
        "send_support_sms" to "সাপোর্ট আপডেট এসএমএস পাঠান",
        "resend_now" to "পুনরায় পাঠান",
        "clear_logs" to "ট্র্যাকার ডাটা মুছুন",
        "backup" to "ডাটাবেজ ব্যাকআপ",
        "backup_title" to "ডাটাবেজ ব্যাকআপ",
        "settings" to "সেটিংস",
        "settings_title" to "সেটিংস",
        "logout" to "লগআউট",
        "nav_dashboard" to "ড্যাশবোর্ড",
        "nav_customers" to "গ্রাহক",
        "nav_billing" to "বিলিং",
        "nav_payments" to "পেমেন্ট",
        "nav_router" to "রাউটার",

        // Customer Ledger
        "customer_ledger" to "গ্রাহক হিসাব খাতা (লেজার)",
        "view_ledger" to "সম্পূর্ণ লেজার দেখুন",
        "ledger_summary" to "আর্থিক সারসংক্ষেপ",
        "ledger_timeline" to "লেজার টাইমলাইন",
        "current_due" to "বর্তমান বকেয়া",
        "previous_due" to "পূর্বের বকেয়া",
        "carry_forward_due" to "ক্যারি ফরোয়ার্ড বকেয়া",
        "total_generated_bill" to "মোট তৈরি বিল",
        "total_paid" to "মোট জমা / পরিশোধিত",
        "total_discount" to "মোট ডিসকাউন্ট",
        "total_advance" to "মোট অগ্রিম",
        "net_outstanding" to "সর্বমোট নিট পাওনা",
        "running_balance" to "চলতি জের / পাওনা",
        "add_ledger_entry" to "লেজার এন্ট্রি যোগ করুন",
        "download_receipt" to "ডাউনলোড রসিদ",
        "print_receipt" to "প্রিন্ট রসিদ",
        "share_receipt" to "শেয়ার রসিদ",
        "export_ledger" to "স্টেটমেন্ট এক্সপোর্ট",
        "filter_type" to "ফিল্টার ধরণ",
        "all_types" to "সকল লেনদেন",
        "entry_type" to "লেনদেনের ধরণ",
        "monthly_bill" to "মাসিক বিল",
        "payment" to "পেমেন্ট / জমা",
        "discount" to "ডিসকাউন্ট",
        "advance" to "এডভান্স / অগ্রিম",
        "adjustment" to "এডজাস্টমেন্ট",
        "carry_forward" to "ক্যারি ফরোয়ার্ড বকেয়া",
        "manual_charge" to "ম্যানুয়াল চার্জ",
        "refund" to "রিফান্ড / ফেরত",
        "waiver" to "ওয়েভার / মওকুফ",

        // Auth
        "login_title" to "নেটবিল আইএসপি সফটওয়্যার",
        "login_subtitle" to "বাংলাদেশের জন্য প্রফেশনাল আইএসপি বিলিং অ্যাপ",
        "username" to "ইউজারনেম",
        "password" to "পাসওয়ার্ড",
        "mobile_number" to "মোবাইল নম্বর (01XXXXXXXXX)",
        "login_btn" to "ড্যাশবোর্ডে প্রবেশ করুন",
        "role" to "দায়িত্ব / রোল",
        "super_admin" to "সুপার এডমিন",
        "manager" to "ম্যানেজার",
        "billing_operator" to "বিলিং অপারেটর",
        "support_staff" to "সাপোর্ট কর্মী",
        "use_mobile_login" to "মোবাইল নম্বর দিয়ে প্রবেশ করুন",
        "use_user_pass_login" to "ইউজারনেম ও পাসওয়ার্ড ব্যবহার করুন",
        "login_success" to "সফলভাবে লগইন করেছেন!",
        "invalid_credentials" to "ইউজারনেম অথবা পাসওয়ার্ড ভুল হয়েছে",

        // Dashboard
        "total_customers" to "মোট গ্রাহক",
        "todays_collection" to "আজকের আদায়",
        "collection_breakdown" to "আদায়ের খাতভিত্তিক বিবরণ",
        "yesterday" to "গতকাল",
        "last_7_days" to "গত ৭ দিন",
        "this_month" to "চলতি মাস",
        "custom_date" to "কাস্টম তারিখ",
        "total_transactions" to "মোট ট্রানজেকশন",
        "avg_collection" to "গড় আদায়",
        "highest_collection" to "সর্বোচ্চ একক",
        "lowest_collection" to "সর্বনিম্ন একক",
        "other_methods" to "অন্যান্য",
        "grand_total" to "সর্বমোট আদায়",
        "select_date" to "তারিখ নির্বাচন",
        "monthly_collection" to "চলতি মাসের আদায়",
        "total_due" to "মোট বকেয়া",
        "todays_expense" to "আজকের খরচ",
        "monthly_expense" to "রানিং মাসের খরচ",
        "active_customers" to "সক্রিয় গ্রাহক",
        "expired_customers" to "এক্সপায়ার গ্রাহক",
        "inactive_customers" to "ইনঅ্যাক্টিভ গ্রাহক",
        "new_customers" to "নতুন গ্রাহক (এই মাসে)",
        "bandwidth_usage" to "লাইভ ব্যান্ডউইথ ব্যবহার",
        "monthly_income_graph" to "মাসিক আয়ের বিশ্লেষণ",
        "expense_graph" to "খরচের খাতসমূহ",
        "customer_growth" to "গ্রাহক বৃদ্ধির ধারা",
        "quick_actions" to "দ্রুত কাজসমূহ",
        "add_customer" to "নতুন গ্রাহক যোগ করুন",
        "collect_payment" to "পেমেন্ট রিসিভ",
        "generate_bills" to "মাসিক বিল জেনারেট করুন",
        "grid_collection" to "কালেকশন",
        "grid_collection_report" to "কালেকশন রিপোর্ট",
        "grid_list_report" to "লিস্ট রিপোর্ট",
        "grid_due_list" to "বকেয়া তালিকা",
        "grid_create_new" to "নতুন গ্রাহক",
        "grid_search" to "অনুসন্ধান",
        "grid_complaint_list" to "অভিযোগ তালিকা",
        "grid_bill_summary" to "বিল সামারি",

        // Customer Management
        "customer_crm" to "গ্রাহক সিআরএম",
        "customer_id" to "কাস্টমার আইডি",
        "customer_name" to "গ্রাহকের নাম",
        "alt_mobile" to "বিকল্প মোবাইল",
        "address" to "ঠিকানা",
        "zone" to "জোন",
        "sub_zone" to "সাব জোন",
        "network_box" to "নেটওয়ার্ক বক্স (টিজে/স্প্লিটার)",
        "package_name" to "ইন্টারনেট প্যাকেজ",
        "monthly_bill" to "মাসিক বিল (৳)",
        "pppoe_username" to "PPPoE ইউজারনেম",
        "pppoe_password" to "PPPoE পাসওয়ার্ড",
        "ip_address" to "আইপি এড্রেস",
        "mac_address" to "ম্যাক এড্রেস",
        "connection_type" to "সংযোগের ধরন",
        "join_date" to "যোগদানের তারিখ",
        "expire_date" to "মেয়াদ শেষের তারিখ",
        "status" to "অবস্থা",
        "active" to "সক্রিয়",
        "inactive" to "নিষ্ক্রিয়",
        "suspended" to "সাময়িক স্থগিত",
        "ref_name" to "রেফারেন্স নাম",
        "ref_mobile" to "রেফারেন্স মোবাইল",
        "current_due" to "বর্তমান বকেয়া",
        "notes" to "বিশেষ মন্তব্য",
        "search_customer" to "নাম (বাংলা/ইংরেজি), আইডি, ফোন বা PPPoE দিয়ে খুঁজুন...",
        "filter_zone" to "জোন ফিল্টার",
        "filter_package" to "প্যাকেজ ফিল্টার",
        "filter_status" to "স্ট্যাটাস ফিল্টার",
        "due_customers" to "শুধু বকেয়া গ্রাহক",
        "all_zones" to "সকল জোন",
        "all_packages" to "সকল প্যাকেজ",
        "all_status" to "সকল স্ট্যাটাস",
        "save_customer" to "গ্রাহক তথ্য সংরক্ষণ করুন",
        "edit_customer" to "তথ্য সংশোধন",
        "delete_customer" to "গ্রাহক মুছে ফেলুন",
        "customer_saved" to "গ্রাহকের তথ্য সফলভাবে সংরক্ষিত হয়েছে",

        // Expiry Alert & Customer Expiry Management
        "customer_expiry_alert_title" to "গ্রাহকের মেয়াদ শেষ হওয়ার সতর্কতা",
        "customer_expiry_alert_desc" to "যেসব গ্রাহকের ইন্টারনেটের মেয়াদ আগামীকাল শেষ হতে যাচ্ছে।",
        "expiring_tomorrow_count" to "জন গ্রাহকের লাইনের মেয়াদ আগামীকাল শেষ হবে।",
        "view_alerts" to "এলার্ট দেখুন",
        "no_upcoming_expiry" to "আসন্ন কোনো মেয়াদ শেষের সতর্কতা নেই",
        "expiring_tomorrow" to "মেয়াদ শেষ হতে যাচ্ছে (আগামীকাল)",
        "expired" to "মেয়াদ শেষ",
        "total_due" to "সর্বমোট বকেয়া",
        "expire_date" to "মেয়াদ শেষের তারিখ",
        "expire_time" to "মেয়াদ শেষের সময়",
        "extend_expiry" to "মেয়াদ পরিবর্তন করুন",
        "update_expiry" to "মেয়াদ সংরক্ষণ করুন",
        "customer_name" to "গ্রাহকের নাম",
        "address" to "ঠিকানা",
        "mobile_number" to "মোবাইল নম্বর",

        // 20th Day Rule
        "day_20_rule_title" to "বিশেষ বিলিং রুল (২০ তারিখের পর সংযোগ)",
        "day_20_rule_desc" to "এই গ্রাহক চলতি মাসের ২০ তারিখের পর যোগদান করেছেন। বিল কীভাবে জেনারেট করবেন?",
        "gen_current_month" to "চলতি মাসের বিল এখনই জেনারেট করুন",
        "gen_next_month" to "আগামী মাস থেকে বিল শুরু করুন",
        "day_20_deadline_alert_title" to "গ্রাহকের মেয়াদ শেষ হওয়ার সতর্কতা",
        "day_20_deadline_alert_desc" to "যে সকল গ্রাহকের লাইনের মেয়াদ আগামীকাল শেষ হবে তাদের তালিকা।",
        "overdue_20th_count" to "আগামীকাল মেয়াদ শেষ হতে যাওয়া গ্রাহক",
        "overdue_20th_amount" to "সর্বমোট বকেয়া পরিমাণ",
        "send_sms_all_20th" to "সকল বকেয়া গ্রাহককে এসএমএস রিমাইন্ডার পাঠান",
        "suspend_all_20th" to "মেয়াদ উত্তীর্ণ লাইন স্থগিত (Suspend) করুন",
        "dismiss_alert" to "অ্যালার্ট বন্ধ করুন",
        "deadline_status_active" to "আগামীকাল মেয়াদ শেষ হবে!",

        // MikroTik
        "mikrotik_title" to "মাইক্রোটিক রাউটার কন্ট্রোল",
        "router_status" to "রাউটার স্ট্যাটাস",
        "router_ip" to "রাউটার আইপি",
        "online_users" to "অনলাইন PPPoE ইউজার",
        "user_traffic" to "লাইভ ইউজার ট্রাফিক",
        "enable_user" to "সংযোগ চালু করুন",
        "disable_user" to "সংযোগ বন্ধ করুন (ডিজেবল)",
        "change_package" to "স্পিড/প্যাকেজ পরিবর্তন",
        "router_connected" to "সংযুক্ত আছে (RouterOS v7.12)",
        "router_disconnected" to "সংযোগ বিচ্ছিন্ন / যাচাই করা হচ্ছে...",
        "sync_mikrotik" to "রাউটার সিঙ্ক করুন",

        // Billing Module
        "billing_management" to "বিলিং ও ইনভয়েস",
        "invoice_no" to "ইনভয়েস নং",
        "billing_month" to "বিলিং মাস",
        "paid" to "পরিশোধিত",
        "unpaid" to "অপরিবেশোধিত (বকেয়া)",
        "partial" to "আংশিক পরিশোধ",
        "generate_monthly_invoices" to "স্বয়ংক্রিয় মাসিক বিল তৈরি করুন",
        "bills_generated" to "মাসিক বিল ইনভয়েস সফলভাবে জেনারেট হয়েছে!",
        "late_fee" to "বিলম্ব ফি",
        "previous_due" to "পূর্বের বকেয়া",
        "total_payable" to "সর্বমোট প্রদেয়",

        // Payment Collection
        "payment_collection" to "পেমেন্ট কালেকশন",
        "amount" to "টাকার পরিমাণ (৳)",
        "payment_method" to "পেমেন্ট মেথড",
        "bkash" to "বিকাশ (bKash)",
        "nagad" to "নগদ (Nagad)",
        "rocket" to "রকেট (Rocket)",
        "cash" to "ক্যাশ / নগদ টাকা",
        "bank_transfer" to "ব্যাংক ট্রান্সফার",
        "transaction_id" to "ট্রানজেকশন আইডি / রেফারেন্স",
        "payment_date" to "পেমেন্টের তারিখ",
        "collector_name" to "সংগ্রহকারী নাম",
        "remarks" to "মন্তব্য",
        "record_payment" to "পেমেন্ট জমা দিন",
        "payment_success" to "পেমেন্ট সফলভাবে জমা নেওয়া হয়েছে!",
        "view_receipt" to "রশিদ দেখুন / প্রিন্ট",
        "print_receipt" to "পিডিএফ রিসিভ প্রিন্ট",
        "share_whatsapp" to "হোয়াটসঅ্যাপে মানি রিসিভ পাঠাও",
        "send_sms" to "এসএমএস নোটিফিকেশন পাঠাও",

        // Expenses
        "expense_management" to "দৈনন্দিন খরচের হিসাব",
        "add_expense" to "নতুন খরচ যোগ করুন",
        "expense_category" to "খরচের খাত",
        "bandwidth_cost" to "ব্যান্ডউইথ খরচ",
        "staff_salary" to "স্টাফ বেতন",
        "electricity_bill" to "বিদ্যুৎ বিল",
        "equipment_purchase" to "যন্ত্রাংশ ক্রয় (অনু, কেবল, স্প্লিটার)",
        "office_rent" to "অফিস ভাড়া",
        "maintenance" to "রক্ষণাবেক্ষণ খরচ",
        "transport" to "যাতায়াত খরচ",
        "other_expense" to "অন্যান্য খরচ",

        // Staff
        "staff_management" to "স্টাফ ও কর্মচারী তালিকা",
        "staff_name" to "কর্মচারীর নাম",
        "salary" to "মাসিক বেতন",
        "joining_date" to "যোগদানের তারিখ",
        "pay_salary" to "বেতন প্রদান করুন",
        "salary_ledger" to "বেতন হিসাব (লেজার)",
        "total_salary_accrued" to "মোট অর্জিত বেতন",
        "total_disbursed" to "মোট পরিশোধিত",
        "net_balance" to "নিট ব্যালেন্স",
        "pao_na" to "পাওনা",
        "advance" to "অগ্রিম",
        "date_month" to "তারিখ ও মাস",
        "transaction_type" to "লেনদেনের ধরণ",
        "amount_label" to "পরিমাণ",
        "account_balance" to "হিসাব ব্যালেন্স",
        "remarks_label" to "মন্তব্য",
        "salary_accrued" to "বেতন যোগ হয়েছে",
        "cash_disbursed" to "নগদ পরিশোধ",
        "running_bal" to "মোট পাওনা",
        "no_records" to "কোন তথ্য পাওয়া যায়নি",
        "edit_salary_record" to "স্যালারি রেকর্ড এডিট",
        "delete_record" to "রেকর্ড মুছুন",
        "confirm_delete_payout" to "আপনি কি নিশ্চিত যে এই স্যালারি রেকর্ডটি মুছতে চান? স্টাফ ব্যালেন্স সমন্বয় করা হবে।",
        "update_record" to "রেকর্ড আপডেট",
        "cancel" to "বাতিল",
        "target_month" to "লক্ষ্য মাস",
        "payroll_report" to "পেরোল রিপোর্ট",

        // Packages
        "package_management" to "ইন্টারনেট প্যাকেজসমূহ",
        "speed" to "ব্যান্ডউইথ স্পিড",
        "monthly_price" to "মাসিক বিল (৳)",
        "add_package" to "নতুন প্যাকেজ যোগ করুন",

        // Reports
        "reports_analytics" to "রিপোর্ট ও এনালিটিক্স",
        "daily_collection_report" to "দৈনিক কালেকশন রিপোর্ট",
        "monthly_collection_report" to "মাসিক কালেকশন রিপোর্ট",
        "due_report" to "বকেয়া গ্রাহকদের রিপোর্ট",
        "expense_report" to "খরচের রিপোর্ট",
        "profit_loss_report" to "লাভ-ক্ষতির হিসাব",
        "export_pdf" to "পিডিএফ ডাউনলোড",
        "export_excel" to "সিএসভি/এক্সেল রফতানি",

        // Settings
        "isp_name" to "আইএসপি কোম্পানির নাম",
        "isp_logo" to "কোম্পানির লোগো",
        "support_number" to "কাস্টমার কেয়ার হেল্পলাইন",
        "language_setting" to "ভাষা পরিবর্তন (Language)",
        "currency_setting" to "মুদ্রা সেটিংস",
        "save_settings" to "তথ্য সংরক্ষণ করুন",
        "settings_saved" to "সেটিংস আপডেট হয়েছে!",
        "switch_to_bangla" to "বাংলা ভাষায় পরিবর্তন করুন",
        "switch_to_english" to "Switch to English"
    )

    fun get(key: String, lang: AppLanguage): String {
        val dictionary = if (lang == AppLanguage.BANGLA) bn else en
        return dictionary[key] ?: en[key] ?: key
    }
}

@Composable
fun AppTranslation(key: String): String {
    val currentLang = LocalAppLanguage.current
    return Strings.get(key, currentLang)
}
